[package]
name = "weather_track"
version = "1.0.0"
edition = "2021"

[dependencies]
actix-web = "4.10.2"
askama = "0.12.1"
chrono = "0.4.40"
reqwest = "0.12.14"
rusqlite = "0.34.0"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
